//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music.data
{
    using System;
    using System.Collections.Generic;
     
    
    public partial class Song
    {
        public int song_id { get; set; }
        public string title { get; set; }
        public int relesed { get; set; }
        public string genre { get; set; }
        public Nullable<int> fk_artist_id { get; set; }
        public Nullable<int> fk_album_id { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
    }
}
